spring:
  application:
    name: brideside-backend
  
  # Timezone Configuration
  jackson:
    time-zone: Asia/Kolkata
  
  # Database Configuration
  datasource:
    url: jdbc:mysql://${DB_HOST:thebrideside.mysql.database.azure.com:3306}/${DB_DATABASE:thebrideside}?useSSL=${DB_SSL:true}&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata&characterEncoding=UTF-8&useUnicode=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&createDatabaseIfNotExist=true
    username: ${DB_USER:thebrideside}
    password: ${DB_PASSWORD:TheBride@260799}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:20}
      minimum-idle: ${DB_MIN_IDLE:5}
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 20000
      leak-detection-threshold: 60000
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: ${JPA_FORMAT_SQL:false}
        jdbc:
          batch_size: 20
          time_zone: Asia/Kolkata
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
  
  # Cache Configuration
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=30m
  
  # Security Configuration
  security:
    user:
      name: ${ADMIN_USERNAME:admin}
      password: ${ADMIN_PASSWORD:admin123}
      roles: ADMIN

# Server Configuration
server:
  port: ${SERVER_PORT:8080}
  forward-headers-strategy: framework
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:}
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  http2:
    enabled: true
  tomcat:
    max-threads: 200
    min-spare-threads: 10
    connection-timeout: 20000
    max-connections: 8192

# Management and Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,configprops
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      show-components: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5,0.95,0.99
      slo:
        http.server.requests: 50ms,100ms,200ms,500ms

# Logging Configuration
logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    com.brideside: ${LOG_LEVEL_APP:DEBUG}
    org.springframework.web: ${LOG_LEVEL_WEB:DEBUG}
    org.springframework.security: ${LOG_LEVEL_SECURITY:DEBUG}
    org.hibernate.SQL: ${LOG_LEVEL_SQL:DEBUG}
    org.hibernate.type.descriptor.sql.BasicBinder: ${LOG_LEVEL_SQL_PARAMS:TRACE}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"
  file:
    name: ${LOG_FILE_PATH:logs/brideside-backend.log}
    max-size: ${LOG_FILE_MAX_SIZE:10MB}
    max-history: ${LOG_FILE_MAX_HISTORY:30}

# API Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    oauth2-redirect-url: /swagger-ui/oauth2-redirect.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
  show-actuator: false

# Pipedrive Configuration
pipedrive:
  api:
    token: ${PIPEDRIVE_API_TOKEN:3300616fba6c2bfd07d314a14520786791f1d20e}
    base-url: ${PIPEDRIVE_BASE_URL:https://acceltancy4.pipedrive.com}
    org-id: ${PIPEDRIVE_ORG_ID:41}
  deal:
    pipeline-id: ${PIPEDRIVE_PIPELINE_ID:13}
    custom-fields:
      event-type: ${PIPEDRIVE_DEAL_EVENT_TYPE_FIELD:accd9fb1f4d3f8908a76936061144431b98352e6}
      event-date: ${PIPEDRIVE_DEAL_EVENT_DATE_FIELD:7b61d5c385508aa4cef1a30d7c3b350209670f39}
      venue: ${PIPEDRIVE_DEAL_VENUE_FIELD:477fb2ebb13a363c7bf614255f42c8133c9f2447}
      dealSource: ${PIPEDRIVE_DEAL_SOURCE_FIELD:ae66e7601c2787449fe3e796ac803fc62645a22b}
  person:
    custom-fields:
      personSource: ${PIPEDRIVE_PERSON_SOURCE_FIELD:bb67874cea1b01f4eadb549eda0033ff530ea0ba}

# WhatsApp Configuration
whatsapp:
  base-url: ${WHATSAPP_BASE_URL:https://graph.facebook.com/v22.0}
  phone-number-id: ${WHATSAPP_PHONE_NUMBER_ID:812190678648433}
  access-token: ${WHATSAPP_ACCESS_TOKEN:EAARqbESmhd8BP4uCE7ZCByZC63F7v5mouajpe2jDaOPuDfC1PncFHTkFwDlUfoffy8QqeGa9iosuP8y4IAdVR8w2F90E7EdPxgmLftV8gimpD9Bp3pcUH1tKmngrWxVw58QPA698lhEjxlUxQZC4OZAnIRGnLPnluECQDgfBYuc4bXeajTri0o0j892qgQZDZD}

# Application Info
info:
  app:
    name: ${spring.application.name}
    description: Brideside Backend API
    version: @project.version@
    java:
      version: @java.version@
  build:
    artifact: @project.artifactId@
    group: @project.groupId@
    name: @project.name@
    time: ${maven.build.timestamp}
    version: @project.version@
