spring:
  config:
    activate:
      on-profile: azure
  
  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
  
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

# Server Configuration for Azure
server:
  port: ${PORT:8080}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:}

# Logging Configuration for Azure
logging:
  level:
    root: WARN
    com.brideside: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
  file:
    name: /home/LogFiles/application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Management endpoints for Azure monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      azure-monitor:
        enabled: false  # Disable if not using Azure Monitor

# API Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
  show-actuator: false
