# Azure App Service Configuration
# This file contains Azure-specific deployment settings

apiVersion: 2021-02-01
kind: WebApp
properties:
  name: brideside-backend
  resourceGroup: brideside-rg
  location: "East US"
  kind: app,linux,container
  reserved: true
  siteConfig:
    linuxFxVersion: "DOCKER|your-registry.azurecr.io/brideside-backend:latest"
    appSettings:
      - name: "WEBSITES_ENABLE_APP_SERVICE_STORAGE"
        value: "false"
      - name: "DOCKER_REGISTRY_SERVER_URL"
        value: "https://your-registry.azurecr.io"
      - name: "DOCKER_REGISTRY_SERVER_USERNAME"
        value: "your-registry"
      - name: "DOCKER_REGISTRY_SERVER_PASSWORD"
        value: "your-password"
      - name: "SPRING_PROFILES_ACTIVE"
        value: "azure"
      - name: "TZ"
        value: "Asia/Kolkata"
      - name: "JAVA_OPTS"
        value: "-Duser.timezone=Asia/Kolkata"
      - name: "DB_HOST"
        value: "thebrideside.mysql.database.azure.com:3306"
      - name: "DB_DATABASE"
        value: "thebrideside"
      - name: "DB_USER"
        value: "thebrideside"
      - name: "DB_PASSWORD"
        value: "TheBride@260799"
      - name: "DB_SSL"
        value: "true"
      - name: "ADMIN_USERNAME"
        value: "admin"
      - name: "ADMIN_PASSWORD"
        value: "admin123"
    alwaysOn: true
    httpLoggingEnabled: true
    detailedErrorLoggingEnabled: true
    requestTracingEnabled: true
