global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'brideside-backend'
    static_configs:
      - targets: ['brideside-backend:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
