CREATE TABLE IF NOT EXISTS `deals` (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    contact_number VARCHAR(20) NOT NULL,
    category VARCHAR(50) NOT NULL,
    event_date DATE,
    event_dates JSON,
    venue TEXT,
    budget DECIMAL(10,2),
    `value` DECIMAL(12,2) NOT NULL DEFAULT 0,
    expected_gathering INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    pipedrive_deal_id VARCHAR(100),
    person_id BIGINT,
    pipeline_id BIGINT,
    organization_id BIGINT,
    status ENUM('WON','LOST','IN_PROGRESS') NOT NULL,
    category_id BIGINT,
    deal_source VARCHAR(50),
    deal_sub_source ENUM('INSTAGRAM','WHATSAPP','LANDING_PAGE','EMAIL'),
    created_by ENUM('USER','BOT'),
    created_by_name VARCHAR(255),
    created_by_user_id BIGINT,
    stage_id BIGINT
);

CREATE TABLE IF NOT EXISTS `persons` (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    phone VARCHAR(50),
    phone_num VARCHAR(255),
    source VARCHAR(255),
    person_source ENUM('INSTAGRAM','WHATSAPP','TBS_WEBSITE','REFERRAL','OTHER'),
    sub_source ENUM('INSTAGRAM','WHATSAPP','LANDING_PAGE','EMAIL'),
    venue TEXT,
    wedding_date VARCHAR(255),
    lead_date DATE,
    organization_id BIGINT,
    owner_id BIGINT,
    category_id BIGINT,
    is_deleted BIT(1) NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
